spring:
    datasource:
        password: 1423
        url: jdbc:mysql://localhost:3306/server_01_db?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect


application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # 1 day
            refresh-token:
                expiration: 604800000 # 7 days
